#!/usr/bin/env python3
"""
build_angle.py - Automated script to clone, configure and compile Google ANGLE for Android (arm64-v8a)
using Android NDK on Windows.
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
ANDROID_DIR = WORKSPACE_ROOT / "android"
JNILIBS_ARM64 = ANDROID_DIR / "app" / "src" / "main" / "jniLibs" / "arm64-v8a"
BUILD_DIR = WORKSPACE_ROOT / "build_angle"

def find_ndk() -> Path:
    # 1. Environment variables
    for var in ["ANDROID_NDK_HOME", "ANDROID_NDK_ROOT", "NDK_ROOT"]:
        val = os.environ.get(var)
        if val and Path(val).exists():
            return Path(val)

    # 2. android/local.properties
    local_props = ANDROID_DIR / "local.properties"
    if local_props.exists():
        sdk_dir = None
        ndk_dir = None
        with open(local_props, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if line.startswith("ndk.dir="):
                    ndk_dir = line.split("=", 1)[1].replace("\\:", ":").replace("\\\\", "\\")
                elif line.startswith("sdk.dir="):
                    sdk_dir = line.split("=", 1)[1].replace("\\:", ":").replace("\\\\", "\\")
        if ndk_dir and Path(ndk_dir).exists():
            return Path(ndk_dir)
        if sdk_dir:
            ndk_base = Path(sdk_dir) / "ndk"
            if ndk_base.exists():
                versions = sorted(list(ndk_base.iterdir()), reverse=True)
                if versions:
                    return versions[0]

    # 3. Default user paths
    default_ndk = Path(os.path.expanduser("~")) / "AppData" / "Local" / "Android" / "Sdk" / "ndk"
    if default_ndk.exists():
        versions = sorted(list(default_ndk.iterdir()), reverse=True)
        if versions:
            return versions[0]

    raise RuntimeError("Android NDK not found. Please set ANDROID_NDK_HOME or check android/local.properties")

def find_ninja() -> str:
    ninja = shutil.which("ninja")
    if ninja:
        return ninja
    common_paths = [
        Path("C:/arm-eabi/bin/ninja.exe"),
        Path("C:/ninja/ninja.exe"),
    ]
    for p in common_paths:
        if p.exists():
            return str(p)
    raise RuntimeError("Ninja not found in PATH or standard locations.")

def clone_angle(dest: Path):
    if not dest.exists():
        print(f"[*] Cloning Google ANGLE into {dest}...")
        subprocess.run(["git", "clone", "--depth", "1", "https://github.com/google/angle.git", str(dest)], check=True)
    else:
        print(f"[*] ANGLE source repository already present at {dest}")

def main():
    print("==================================================================")
    print("  Google ANGLE Android (arm64-v8a) Builder for OpenXRay")
    print("==================================================================")

    ndk_path = find_ndk()
    ninja_path = find_ninja()
    print(f"[+] Using NDK:   {ndk_path}")
    print(f"[+] Using Ninja: {ninja_path}")
    print(f"[+] Output dir:  {JNILIBS_ARM64}")

    JNILIBS_ARM64.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    angle_src = BUILD_DIR / "angle"
    clone_angle(angle_src)

    out_dir = angle_src / "out" / "Android_arm64"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Prepare args.gn
    ndk_posix = str(ndk_path).replace("\\", "/")
    import platform as _platform

    _host_os = _platform.system()
    if _host_os == "Windows":
        _ndk_host_tag = "windows-x86_64"
    elif _host_os == "Darwin":
        _ndk_host_tag = "darwin-x86_64"
    else:
        _ndk_host_tag = "linux-x86_64"
    ndk_llvm_prebuilt = ndk_posix + "/toolchains/llvm/prebuilt/" + _ndk_host_tag
    gn_args_content = f"""# Auto-generated by build_angle.py
target_os = "android"
target_cpu = "arm64"
is_debug = false
is_component_build = false
angle_enable_vulkan = true
angle_enable_gl = true
angle_enable_d3d9 = false
angle_enable_d3d11 = false
angle_enable_metal = false
angle_enable_null = false
enable_rust = false
angle_enable_perfetto = false
use_custom_libunwind = false
use_custom_libcxx = false
clang_use_chrome_plugins = false
angle_build_all = false
angle_build_tests = false
android_ndk_root = "{ndk_posix}"
default_min_sdk_version = 24
android_ndk_api_level = 24
clang_base_path = "{ndk_llvm_prebuilt}"
clang_version = "19"
angle_libs_suffix = "_angle"
"""
    with open(out_dir / "args.gn", "w", encoding="utf-8") as f:
        f.write(gn_args_content)

    print(f"[+] Generated {out_dir / 'args.gn'}")

    gn_path = shutil.which("gn") or shutil.which("gn.exe")
    if not gn_path:
        for p in [
            BUILD_DIR / "tools" / "gn.exe",
            Path("C:/gn/gn.exe"),
            Path("C:/depot_tools/gn.bat"),
            Path("C:/depot_tools/gn.exe"),
        ]:
            if p.exists():
                gn_path = str(p)
                break

    if gn_path:
        print(f"[*] Found GN at: {gn_path}")
        print(f"[*] Generating ninja files via 'gn gen {out_dir}'...")
        res = subprocess.run([gn_path, "gen", str(out_dir)], cwd=str(angle_src))
        if res.returncode == 0:
            print(f"[*] Building libEGL and libGLESv2 with Ninja...")
            build_res = subprocess.run([ninja_path, "-C", str(out_dir), "libEGL", "libGLESv2"], cwd=str(angle_src))
            if build_res.returncode == 0:
                print(f"[+] Build succeeded! Copying libraries to {JNILIBS_ARM64}...")
                for lib_name in ["libEGL_angle.so", "libGLESv2_angle.so", "libEGL.so", "libGLESv2.so"]:
                    built_file = out_dir / lib_name
                    if built_file.exists():
                        target_name = lib_name if "_angle" in lib_name else lib_name.replace(".so", "_angle.so")
                        target_path = JNILIBS_ARM64 / target_name
                        shutil.copy2(built_file, target_path)
                        print(f"  -> Installed {target_path}")
                print("[+] ANGLE libraries installation complete!")
                return
    else:
        print("[!] Note: 'gn' (Generate Ninja) was not found in PATH.")
        print("    To complete compilation:")
        print("    1) Place 'gn.exe' in your PATH or in C:\\gn\\gn.exe")
        print(f"    2) Run: gn gen {out_dir}")
        print(f"    3) Run: {ninja_path} -C {out_dir} libEGL libGLESv2")
        print(f"    4) Copy the resulting .so files to: {JNILIBS_ARM64}")

if __name__ == "__main__":
    main()
